### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by hummuscience** [JustinaZ/pcaReduce#1]
Hello,

I tried to install the package by downloading the clone and using the following:

`install.packages("path to pcaReduce-master folder", repos = NULL, type = "source")`

And got the following error:
`During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
ERROR: dependency 'mclust' is not available for package 'pcaReduce'
- removing '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/pcaReduce'
  Warning in install.packages :
  installation of package '/Users/muadabdelhay/Downloads/pcaReduce-master' had non-zero exit status`

I also tried the same using the path to the R folder in the zip file, it did not work either.

Any idea how I could resolve this issues?

I am on OSX 10.11.6 with the R version 3.3.1 (2016-06-21)

**Comment by JustinaZ** [comment]
Hi,
Do you have all other packages (i.e. pcaMethods, mnormt, mclust) installed? If not, maybe try installing them first, and then try again installing pcaReduce:

 install.packages("/Users/muadabdelhay/Downloads/pcaReduce-master", repos = NULL, type = "source")

This --  "ERROR: dependency 'mclust' is not available for package 'pcaReduce' " I think tells you that you don't have mclust on your machine...
