### ISSUE TITLE
installation error with R 3.6.0

### ISSUE THREAD

**Issue by joemsong** [JustinaZ/pcaReduce#3]
Package was installed successfully on previous R version. With the latest R 3.6.0, I got the following error message:

> devtools::install_github("JustinaZ/pcaReduce")
Downloading GitHub repo JustinaZ/pcaReduce@master
Skipping 1 packages not available: pcaMethods
✔  checking for file ‘/private/var/folders/ft/g8jhpzcs1rjfmdll56gkw7x00000gn/T/RtmpEArj3I/remotes36c4304abb41/JustinaZ-pcaReduce-eca48bc/DESCRIPTION’ ...
─  preparing ‘pcaReduce’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pcaReduce_1.0.tar.gz’
   
* installing *source* package ‘pcaReduce’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /private/var/folders/ft/g8jhpzcs1rjfmdll56gkw7x00000gn/T/RtmpDTK3Q3/R.INSTALL37172683e18e/pcaReduce/man/pcaReduce-package.Rd:25: All text must be in a section
ERROR: installing Rd objects failed for package ‘pcaReduce’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pcaReduce’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/ft/g8jhpzcs1rjfmdll56gkw7x00000gn/T//RtmpEArj3I/file36c47a4bc12b/pcaReduce_1.0.tar.gz’ had non-zero exit status

**Comment by JustinaZ** [comment]
Hello,
Just installed R 3.6; package does work if you follow description given in README.txt.
If you recently installed latest R version, I think you need to re-install other packages too:

1) pcaMethods which is available from Bioconductor, 
https://www.bioconductor.org/packages/release/bioc/html/pcaMethods.html

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pcaMethods")


2) mnormt 

3) mclust 

Hope this helps.
Regards,
J.

**Comment by joemsong** [comment]
Thank you!

I used install.packages instead of devtools::install_github(). Now it
worked out.

Best regards,

Joe

**Comment by royfrancis** [comment]
I get the following error on installation. I think i have the dependencies already.

```r
devtools::install_github("JustinaZ/pcaReduce")

...
** help
Error : (converted from warning) /tmp/Rtmp9rEOJ7/R.INSTALL17054b74db85/pcaReduce/man/pcaReduce-package.Rd:25: All text must be in a section
ERROR: installing Rd objects failed for package ‘pcaReduce’
* removing ‘/home/roy/R/x86_64-pc-linux-gnu-library/3.6.0/pcaReduce’
Error: Failed to install 'pcaReduce' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpsZaRNe/file1a650210022/pcaReduce_1.0.tar.gz’ had non-zero exit status
>> packageVersion("devtools")
[1] ‘2.2.2’
>> packageVersion("pcaMethods")
[1] ‘1.76.0’
>> packageVersion("mnormt")
[1] ‘1.5.6’
>> packageVersion("mclust")
[1] ‘5.4.5’
>> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS
```

**Comment by royfrancis** [comment]
I downloaded pcaReduce_1.0.tar.gz which worked.
